### ISSUE TITLE
package vulkan-tools

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/vulkan-headers-feedstock#5]
### Comment:

I think it would be nice to have a package for vulkant-tools

https://github.com/KhronosGroup/Vulkan-Tools/

Just leaving it here for future reference

**Comment by hmaarrfk** [comment]
Have you looked into moltenvk? it seems like a dependency to build vulkan-tools on osx:
https://github.com/KhronosGroup/MoltenVK

**Comment by traversaro** [comment]
> Have you looked into moltenvk? it seems like a dependency to build vulkan-tools on osx: https://github.com/KhronosGroup/MoltenVK

It seems to be using xcode as build system, I am not sure how compatible is xcode with conda-forge-provided compilers.
